### PR TITLE
Check if the nlmixr2 installation is successful, and give hints on how to fix it

### PR DESCRIPTION
**Pull request by billdenney**

### CODE REVIEW

**Comment by billdenney** [comment]
This includes the changes in #66

**Comment by mattfidler** [comment]
You cannot change `options(warn)` and remain on CRAN....

**Comment by billdenney** [comment]
That makes sense.  Updated.

**Comment by mattfidler** [comment]
```
W  checking R files for non-ASCII characters
   Found the following file with non-ASCII characters:
     nlmixr2CheckInstall.R
   Portable packages must use only ASCII characters in their R code,
   except perhaps in comments.
   Use \uxxxx escapes for other characters.
```

**Pull request merged**
